#!/bin/bash
set -e

VSMTP_USER="vsmtp"

DPKG_NAME="vsmtp"
DPKG_VER=$(dpkg -s $DPKG_NAME | sed -n 's/^Version: //p')

CONF_DIR="/etc/vsmtp/"
CONF_FILE=${CONF_DIR}"vsmtp.vsl"
USER_CONF_DIR=${CONF_DIR}"conf.d/"
USER_CONF_FILE=${USER_CONF_DIR}"config.vsl"
DOMAIN_AVAILABE_DIR=${CONF_DIR}"domain-availabe/"
DOMAIN_ENABLED_DIR=${CONF_DIR}"domain-enabled/"
SERVICES_DIR=${CONF_DIR}"services/"
OBJECTS_DIR=${CONF_DIR}"objects/"
PLUGINS_DIR=${CONF_DIR}"plugins/"
DYLIB_DIR="/usr/lib/${DPKG_NAME}/${DPKG_VER}/"

PLUGINS_NOMENCLATURE="libvsmtp_plugin_"
PLUGINS=(mysql csv)

LOG_DIR="/var/log/${DPKG_NAME}/"
SPOOL_DIR="/var/spool/${DPKG_NAME}/"

add_user() {
    if id ${VSMTP_USER} >/dev/null 2>&1; then return; fi
    adduser --system --shell /usr/sbin/nologin --no-create-home \
        --group --disabled-password --disabled-login --no-create-home --home /noexistent ${VSMTP_USER}
}

# TOCHECK : Automatic directory creation w/ systemd
# https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# but... "the innermost specified directories will be owned by the user
# and group specified in User= and Group=. If the specified directories
# already exist and their owning user or group do not match the configured
# ones, all files and directories below the specified directories as well
# as the directories themselves will have their file ownership recursively
# changed to match what is configured.
check_dir() {
    # vSMTP log directory.
    if [ ! -d "${LOG_DIR}" ]; then
        mkdir ${LOG_DIR}
        chown ${VSMTP_USER}:${VSMTP_USER} ${LOG_DIR}
        chmod 755 ${LOG_DIR}
    fi
    # vSMTP spool directory.
    if [ ! -d "${SPOOL_DIR}" ]; then
        mkdir ${SPOOL_DIR}
        chown ${VSMTP_USER}:${VSMTP_USER} ${SPOOL_DIR}
        chmod 755 ${SPOOL_DIR}
    fi
    # vSMTP config directory.
    if [ ! -d "${CONF_DIR}" ]; then
        mkdir -p ${USER_CONF_DIR} ${DOMAIN_AVAILABE_DIR} ${DOMAIN_ENABLED_DIR} ${SERVICES_DIR} ${OBJECTS_DIR} ${PLUGINS_DIR}

        chown ${VSMTP_USER}:${VSMTP_USER} ${CONF_DIR} ${DOMAIN_AVAILABE_DIR} ${DOMAIN_ENABLED_DIR} ${SERVICES_DIR} ${OBJECTS_DIR} ${PLUGINS_DIR}
        chmod 755 ${CONF_DIR} ${DOMAIN_AVAILABE_DIR} ${DOMAIN_ENABLED_DIR} ${SERVICES_DIR} ${OBJECTS_DIR} ${PLUGINS_DIR}
    fi
}

check_config() {
    # Root configuration file is always overridden.
    cat >"${CONF_FILE}" <<EOF
//! This is the first file that vSMTP reads when it starts.
//!
//! This file is maintained by vSMTP package maintainers and it is recommended that administrators
//! avoid editing this file unless they also follow changes made by upstream.
//! It's advised to instead add customizations in the files underneath
//! the "conf.d" directory.

import "conf.d/config" as cfg;

fn on_config(config) {
    let config = cfg::on_config(config);

    config.version_requirement = ">=${DPKG_VER}";
    config
}

EOF
    chown ${VSMTP_USER}:${VSMTP_USER} ${CONF_FILE}
    chmod 664 ${CONF_FILE}

    # User defined config file is preserved if it already exists.
    if [ ! -f "${USER_CONF_FILE}" ]; then
        cat >"${USER_CONF_FILE}" <<EOF
//! This is the entrypoint for vSMTP's configuration.
//!
//! To make the configuration easier to maintain, we recommend that you split
//! it into a set of feature-specific files stored in this directory that you
//! can import via the Rhai import statement.
//!
//! See https://vsmtp.rs/ref/config/config.html

fn on_config(config) {
    // Configure vSMTP here using the config variable.
    config.app.vsl.domain_dir = "/etc/vsmtp/domain-enabled";

    // Create the /etc/vsmtp/filter.vsl file and uncomment this line to enable filtering.
    // config.app.vsl.filter_path = "/etc/vsmtp/filter.vsl";

    config
}
EOF
        chown ${VSMTP_USER}:${VSMTP_USER} ${USER_CONF_FILE}
        chmod 664 ${USER_CONF_FILE}
    fi
}

add_plugins_and_symlinks() {
    for plugin in ${PLUGINS[@]}; do
        plugin_name=${PLUGINS_NOMENCLATURE}${plugin}.so

        # Symlink plugins to /etc/vsmtp/plugins directory.
        ln -s ${DYLIB_DIR}${plugin_name} ${PLUGINS_DIR}${plugin_name}
    done
}

case "$1" in
configure)
    add_user
    check_dir
    check_config
    add_plugins_and_symlinks
    ;;
esac

#DEBHELPER#
