#!/bin/bash
set -e

CONF_DIR="/etc/vsmtp/"
VSMTP_LOGS="/var/log/vsmtp/"
VSMTP_SPOOL="/var/spool/vsmtp/"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -d ${CONF_DIR} ]; then
        rm -rf ${CONF_DIR} ${VSMTP_LOGS} ${VSMTP_SPOOL}
    fi
    ;;
esac

#DEBHELPER#
