[package]
edition = "2021"

name = "vsmtp-plugin-vsl"
version = "2.1.1"
license = "GPL-3.0-only"

rust-version = "1.66.1"

authors = ["Team viridIT <https://viridit.com/>"]
description = "The vSL (ViridIT Scripting Language) superset of Rhai for vSMTP"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-rule-engine/"

readme = "../../../README.md"
keywords = ["vsmtp", "scripting-language", "scripting", "rhai"]
categories = ["config"]

[package.metadata.release]
pre-release-replacements = [
    { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp-common\", version = .*", replace = "vsmtp-common = { path = \"../vsmtp-common\", version = \"={{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "=2.1.1" }

rhai = { version = "1.12.0", features = ["unchecked", "sync", "internals", "no_closure", "metadata"] }

strum = { version = "0.24.1", default-features = false, features = ["std", "derive"] }
regex = { version = "1.9.4", default-features = false, features = ["std", "perf", "unicode"] }
iprange = { version = "0.6.7", default-features = false, features = [
    # "serde" # TODO
] }
ipnet = { version = "2.7.1", default-features = false, features = [
    # "serde", # TODO
] }
either = { version = "1.8.1", default-features = false, features = ["use_std"] }
anyhow = { version = "1.0.69", default-features = false, features = ["std"] }
addr = { version = "0.15.6", default-features = false, features = ["std"] }

# Unix feature dependencies.
hostname = { version = "0.3.1", default-features = false, optional = true }
users = { version = "0.11.0", default-features = true, optional = true }

[dev-dependencies]
vsmtp-test = { path = "../vsmtp-test" }

[features]
default = ["objects", "unix"]

# vSL objects, like email addresses, ips or files.
objects = []

# Utils functions to interact with an unix system.
unix = ["hostname", "users"]
